# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArancelPractica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observaciones')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Aranceles de Prácticas',
                'verbose_name': 'Arancel de Práctica',
            },
        ),
        migrations.CreateModel(
            name='CodigoPractica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observaciones')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código de Práctica')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('codigo', 'prestador'),
                'verbose_name_plural': 'Códigos de Prácticas',
                'verbose_name': 'Código de Práctica',
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio del convenio')),
            ],
            options={
                'ordering': ('prestador',),
                'verbose_name_plural': 'Convenios con Prestadores',
                'verbose_name': 'Convenio con Prestador',
            },
        ),
        migrations.CreateModel(
            name='DetalleArancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arancel_homologado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arancel_homologado', to='convenio.ArancelPractica', verbose_name='Arancel Homologado')),
                ('arancel_prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arancel_prestador', to='convenio.ArancelPractica', verbose_name='Arancel del Prestador')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenio.Convenio', verbose_name='Convenio')),
            ],
            options={
                'ordering': ('convenio', 'arancel_prestador'),
                'verbose_name_plural': 'Detalles de Convenio de Aranceles de Práctica',
                'verbose_name': 'Detalle de Convenio de Aranceles de Práctica',
            },
        ),
        migrations.CreateModel(
            name='DetalleCodigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_homologado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigo_homologado', to='convenio.CodigoPractica', verbose_name='Código Homologado')),
                ('codigo_prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_prestador', to='convenio.CodigoPractica', verbose_name='Código del Prestador')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenio.Convenio', verbose_name='Convenio')),
            ],
            options={
                'ordering': ('convenio', 'codigo_prestador'),
                'verbose_name_plural': 'Detalles de Convenio de Códigos de Práctica',
                'verbose_name': 'Detalle de Convenio de Códigos de Práctica',
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Prestador')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Prestadores',
                'verbose_name': 'Prestador',
            },
        ),
        migrations.CreateModel(
            name='SubirExcelCodigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenio.Prestador')),
            ],
        ),
        migrations.AddField(
            model_name='convenio',
            name='prestador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='convenio.Prestador', verbose_name='Prestador'),
        ),
        migrations.AddField(
            model_name='codigopractica',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenio.Prestador'),
        ),
        migrations.AddField(
            model_name='arancelpractica',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenio.Prestador'),
        ),
    ]
