# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio del convenio')),
            ],
            options={
                'ordering': ('prestador',),
            },
        ),
        migrations.CreateModel(
            name='DetalleArancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arancel_homologado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arancel_homologado', to='nomenclador.Arancel', verbose_name='Arancel Homologado')),
                ('arancel_prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arancel_prestador', to='nomenclador.Arancel', verbose_name='Arancel del Prestador')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenio.Convenio', verbose_name='Convenio')),
            ],
            options={
                'ordering': ('convenio', 'arancel_prestador'),
            },
        ),
        migrations.CreateModel(
            name='DetalleCodigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_homologado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_homologado', to='nomenclador.Codigo', verbose_name='Código Homologado')),
                ('codigo_prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_prestador', to='nomenclador.Codigo', verbose_name='Código del Prestador')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenio.Convenio', verbose_name='Convenio')),
            ],
            options={
                'ordering': ('convenio', 'codigo_prestador'),
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Prestador')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='convenio',
            name='prestador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='convenio.Prestador', verbose_name='Prestador'),
        ),
    ]
