# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convenio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenio.Detalle')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_desde', models.DateField(default=django.utils.timezone.now)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('porcentaje_aumento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('P', 'Propuesto'), ('R', 'Renegociado'), ('C', 'Conforme'), ('A', 'Autorizado')], default='P', max_length=1)),
                ('aceptado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_creador', to=settings.AUTH_USER_MODEL)),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='convenio.Prestador')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_modificador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='precio',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precio.SolicitudAumento'),
        ),
    ]
