# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('precio', '0002_auto_20161121_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudaumento',
            name='vigencia_desde',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
